spring:
  datasource:
    url: jdbc:mysql://db-spring.cpw1kq6o4isf.us-east-1.rds.amazonaws.com/spotify___db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ira
    password: Ira_050504
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    # Show or not log for each sql query
    show-sql: true
    hibernate:
      # Hibernate ddl auto (validate, create, create-drop, update)
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  mvc:  # the fix for swagger
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8080
